name: Build and Deploy Flutter Web to Cloudflare Pages
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Create .env file
        run: |
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter Web
        run: flutter build web --release
      - name: Deploy to Cloudflare Pages
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/pages/projects/$PROJECT_NAME/deployments" \
          -H "Authorization: Bearer $CF_API_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{
            "branch": "main",
            "path": "./build/web"
          }'
