name: Build and Deploy Flutter Web to Cloudflare Pages
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Create .env file
        run: |
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter Web
        run: flutter build web --release
      - name: Install Node.js
        uses: actions/setup-node@v2
      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Deploy to Cloudflare Pages
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          wrangler publish ./build/web --project-name ${{ secrets.PROJECT_NAME }} --env production
